spring:
  datasource:
    url: ${PAYMENTS_DB_URL:jdbc:postgresql://localhost:5436/payments_db}
    username: ${PAYMENTS_DB_USERNAME:ecommerce}
    password: ${PAYMENTS_DB_PASSWORD:ecommerce}

logging:
  file:
    name: ${LOG_FILE:logs/payment-service.log}
